[platformio]
default_envs = mega2560

[env:mega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino
build_flags = -std=gnu++11
monitor_speed = 115200

[env:native]
platform = native
build_flags = -std=gnu++11
test_filter = test_azimuth_logic
